os: linux
dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
script: python setup.py test
# command to install dependencies
# install: "pip install . 'coverage<4' coveralls"
# # command to run tests
# script:
#   coverage run --source=pytimeparse setup.py test
# after_success:
#   coveralls
